language: php

php:
  - 7.4
  - 8.0

install:
  - composer install --no-interaction --no-suggest

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml -c app

after_script:
  - php vendor/bin/php-coveralls -v

cache:
  directories:
  - $HOME/.composer/cache
